spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/day15?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: test03
  mail:
    username: 757004980@qq.com
    password: sixojjxacphmbdbg
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.enable: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  file:
    name: log/mybatis-log.log
  level:
    root: warn
    com.shengsiyuan: debug




